### PR TITLE
Update wp hooks dependency renamed wp 6.0 and aliases

### LINKED ISSUE #12: Dynamic hooks trigger `HookNotFound`
Hi, it looks like dynamic hooks aren't supported yet. e.g., `plugin_action_links_{$plugin_file}`:

```
ERROR: HookNotFound - ../../../../../private/tmp/plugin-basic-google-maps-placemarksqDa7oc/settings.php:31:4 - Hook plugin_action_links_basic-google-maps-placemarks/basic-google-maps-placemarks.php not found.

add_filter( 'plugin_action_links_basic-google-maps-placemarks/basic-google-maps-placemarks.php', array( $this, 'addSettingsLink' ) );
```

https://github.com/humanmade/psalm-plugin-wordpress/blob/8fe21386fb4ff63d4253322dc3b8eaa1bb71c99f/Plugin.php#L245

I don't have any thoughts for an elegant solution at the moment, but I'll think about it some more. Worst case, a brute-force approach would probably work, but might have performance issues.

P.S. Thanks for creating this plugin, it's super helpful!

### PR DESCRIPTION
**Pull request by kkmuffme**
This also partially adds the dynamic hook checks requested in https://github.com/humanmade/psalm-plugin-wordpress/issues/12

It's possible to infer all dynamic hooks easily, but this requires a bit more changes I can only PR once my other PRs are merged to avoid having to rebase my PR and fixing tons of conflicts

### CODE REVIEW

**Comment by ntwb** [comment]
Let's get #41 merged and then update this PR to merge

**Comment by paulshryock** [comment]
@kkmuffme what's the state of dynamic hooks? Either from WordPress core or from third-party plugins. Is there some way I can stub dynamic hooks?

In my `psalm.xml`, I have a block like this:

```xml
<plugins>
	<pluginClass class="PsalmWordPress\Plugin">
		<hooks>
			<directory name="stubs/hooks" recursive="true" />
		</hooks>
	</pluginClass>
</plugins>
```

And then I have `stubs/hooks/actions.json` and `stubs/hooks/filters.json`, which look like this:

```json
{
	"$schema": "https://raw.githubusercontent.com/wp-hooks/generator/0.9.0/schema.json",
	"hooks": []
}
```

So I'm familiar with how to stub out individual hooks, but curious what is the recommended approach for dynamic hooks specifically. Or if that's not yet implemented, just looking for a status update.

Thanks!

**Comment by kkmuffme** [comment]
@paulshryock just fyi dynamic hooks work now with https://github.com/psalm/psalm-plugin-wordpress/pull/49
in both directions (the hook name itself is dynamic and/or the add action/filter hook name is dynamic)
If you could test/check that PR if it works for your hook and give feedback there please.

**Comment by paulshryock** [comment]
Hi @kkmuffme, I've just tested #49 and created a small git repo.

https://github.com/paulshryock/test-psalm-wordpress-latest/blob/main/src/functions.php

```bash
composer show | grep psalm
humanmade/psalm-plugin-wordpress      dev-v5-compatibility-and-features faab6d5 WordPress stubs and plugin for Psalm.
vimeo/psalm                           5.16.0                                    A static analysis tool for finding errors in PHP applications
```

I added several dynamic hooks:
- WordPress core hooks
- Third-party plugin hooks
- First-party hooks

And none of these throw a Psalm error! ❤️ 

Screenshot 2023-12-02 at 3 17 31 PM

---

But then I realized that it seems like dynamic hooks are not checked by Psalm at all, regardless of whether or not they are stubbed.

For example, [this third-party hook](https://github.com/paulshryock/test-psalm-wordpress-latest/blob/main/src/functions.php#L36-L43C1) did throw a Psalm error (`HookNotFound`) until I [defined a stub for it](https://github.com/paulshryock/test-psalm-wordpress-latest/blob/main/stubs/hooks/actions.json) (as expected 👍).

But [this dynamic third-party hook which is not stubbed](https://github.com/paulshryock/test-psalm-wordpress-latest/blob/main/src/functions.php#L47-L59) does not throw a Psalm error, and [this dynamic first-party hook which is not stubbed](https://github.com/paulshryock/test-psalm-wordpress-latest/blob/main/src/functions.php#L64-L76) does not throw a Psalm error.

Is this expected behavior?

**Comment by kkmuffme** [comment]
@paulshryock 
- it didn't support dynamic hooks for `add_action`, as that originally didn't make sense - fixed now
- encapsed strings weren't supported, as we never used those, fixed now
- non-stubbed didn't support dynamic hooks at all, as we have all stubbed, so I didn't implement that at the time (but did now)

Please check again now and let me know if it works as expected for you now.

**Comment by paulshryock** [comment]
Hi @kkmuffme, I [upgraded to the latest commit](https://github.com/paulshryock/test-psalm-wordpress-latest/commit/be6c03b52bdd493835bfb769af6d5788cd51d96e).

```bash
composer upgrade humanmade/psalm-plugin-wordpress
```

`composer.lock`:

```diff
-                "reference": "faab6d5e5ae4b1d7ed374ea040524121ed62ab29"
+                "reference": "2d71d096ac6e47354e381b2d110d754a8c311c47"
```

🥳  Now I get those two failures I was expecting:

```plaintext
vendor/bin/psalm
Target PHP version: 8.1 (inferred from current PHP version).
Scanning files...
Analyzing files...



ERROR: HookNotFound - src/functions.php:52:1 - Hook "ep_delete_{$slug}" not found
/**
 * Dynamic third-party action with no stub defined.
 *
 * This should probably throw a Psalm error, but it does not.
 */
add_action(
  "ep_delete_{$slug}",
  function(int $object_id, string $slug): void {
    print json_encode(['object_id' => $object_id, 'slug' => $slug]);
  },
  10,
  2,
);


ERROR: HookNotFound - src/functions.php:69:1 - Hook "{$verb}_some_{$noun}" not found
/*
 * First-party dynamic hook with no stub defined.
 *
 * This should probably throw a Psalm error, but it does not.
 */
add_filter(
  "{$verb}_some_{$noun}",
  function(string $value): string {
    return "hello {$value}!";
  },
  10,
  1,
);


------------------------------
2 errors found
------------------------------

Checks took 0.02 seconds and used 1.949MB of memory
No files analyzed
Psalm was able to infer types for 100% of the codebase
```

And here's what I see in my text editor (as expected):

Screenshot 2023-12-04 at 5 56 35 PM

This looks great! Thank you for the quick work on this; I feel this is an improved user experience.

**Pull request merged**
